### ISSUE TITLE
pip install tldr.py - errors

### ISSUE THREAD

**Issue by AdamGreenhill** [lord63/tldr.py#17]
I decided to move this out of the previous thread for better visibility. 
After successfully installing tldr.py (i.e. by performing `pip install tldr.py`), and creating the ~/.tldrcc (i.e. with `tldr.py init`. I attempt to execute tldr.py and receive the following errors:
.# tldr find sed
Traceback (most recent call last):
  File "/usr/local/bin/tldr", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tldr/cli.py", line 93, in find
    find_page(command)
  File "/usr/local/lib/python2.7/dist-packages/tldr/cli.py", line 28, in find_page
    encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tldr/pages/index.json'

My environment: I am using Debian 8, with Python 2.7. I have also tried this on the latest version of openSUSE tumbleweed and received the same error after performing the same steps.

**Comment by lord63** [comment]
The reason for the problem: `tldr.py` can't find the index.json, which will be used to find the command page.
Where do you put the the tldr repo that contains the man pages? From the error log, it seems that you put it under `/usr/local/lib/python2.7/dist-packages/tldr` folder?

**Comment by AdamGreenhill** [comment]
Oh I see, I was using the tldr installation directory, instead of the tldr-pages directory.

**Comment by lord63** [comment]
Yeah, the directory should be the location that contains the man pages so that we can find the pages. Close it now.

**Comment by ymdatta** [comment]
@AdamGreenhill, Hi Adam, how did you change the directory location to the one that contains man pages as said by @lord63. I am struck there! :(

**Comment by lord63** [comment]
@ymdatta Just open the .tldrrc file(should be `~/.tldrrc`) and just edit `repo_directory` section. Or you can delete the existed .tldrrc file and regenerate the file with `tldr init`.
