### ISSUE TITLE
Double braces on output

### ISSUE THREAD

**Issue by Cerule** [lord63/tldr.py#25]
tldr.py leaves double braces on output. Shouldn't they be shown as underline or such?

For example:
$ tldr find find
  Find files under the given directory tree, recursively.

- Find files by extension:
  find {{root_path}} -name '{{*.ext}}'

- Find files matching path pattern:
  find {{root_path}} -path '{{**/lib/**/*.ext}}'

- Run a command for each file, use {} within the command to access the filename:
  find {{root_path}} -name '{{*.ext}}' -exec {{wc -l {} }}\;

**Comment by lord63** [comment]
Yeah, that's on purpose. I don't want to spend too much time on the styling. It is hard to do well, so I just keep the original face and show it to users. Also easy to distinguish where is the arguments.

I'm not willing to spend too much time on it, it may exhaust my enthusiasm on maintaining the project. I want to keep it as simple as possible. I'm also using tldr.py in my daily life and can still bear with the ugly theme, haha. But maybe I'll improve it in the future, I'll ping you back if it comes.

And sorry for the late response =)
