### ISSUE TITLE
Feature request: optional abbreviated output

### ISSUE THREAD

**Issue by alpreu** [lord63/tldr.py#26]
Hey, I think a great addition would be an option to abbreviate output.
I for example never look at the description of the command. Also useful would be to omit the linebreak between the 'info' and the command like this and only keep the break to the next example:

> - Find files by extension:  
>  find {{root_path}} -name '{{*.ext}}'  
>  
> - Find files matching path pattern: 
> ....  

This is especially useful if you're using a smaller terminal window or a large lineheight.

**Comment by lord63** [comment]
Hi, thanks for you suggestions, but I'm afraid that this feature request won't be accepted. Flexible means complicated, but I want to keep it as simple as possible for now.

However, you can find the source file and edit by yourself.

```
$ which tldr   # find the location you installed tldr.py
$ vim tldr/parser.py  # edit the parser file and adjust the output
```
