### ISSUE TITLE
Can I use the tldr <command> directly without adding the options `find`?

### ISSUE THREAD

**Issue by ramwin** [lord63/tldr.py#27]
I find if I use `tldr ssh`, an error occured:
```
[user@hostname:~] tldr ssh
Usage: tldr [OPTIONS] COMMAND [ARGS]...

Error: No such command "ssh".
```

Is it necessary to add the find command? But the `tldr find tldr` command shows:
```
  Simplified man pages.

- Get typical usages of a command (hint: this is how you got here!):

  tldr {{command}}

- Update the local cache of tldr pages:

  tldr --update

```

**Comment by lord63** [comment]
You should use `$tldr find COMMAND`, `find` is a subcommand like `git push`.

There is a related issue here #24, you may have a look.
