### ISSUE TITLE
Installation process requires reading manual

### ISSUE THREAD

**Issue by t0rum** [lord63/tldr.py#35]
Could you add some autoinstall mod, which clones tldr-pages, then makes install and reindex?
It's strange that tool for not reading long manuals require reading manual to work.

**Comment by lord63** [comment]
> It's strange that tool for not reading long manuals require reading manual to work.

Hahahahahhahahahahhhahahah XD

I'll leave this issue open and need some time to think about it, seems not a very tough problem.

**Comment by t0rum** [comment]
Well, whole purpose of this application(if I get it right) is to create quicker and more convenient way to recall or find some basic use case scenarios without smth like `w3m google.com/search?q=tar+make+zip`.
And so, it would be very useful while setuping new server, when it's common to use huge array of commands, yet, due this issue, user likely just google something once, or twice, or seven, or twenty times, because in every specific case it's just quicker. 
Yes, each and every user knows, how to use shell scripts. But if he setups new server every year, not every week, it's not very reasonable to write a script. Or install app in the first place. Because _"I'd install app to all servers, it's only two commands"_ would not happend, and instead we have _"well, i'd installed app in my test environment, but it it's too much of a hassle, so I guess I'd just dump it, and never use it again"_ case. 

People are lazy. They like convinience. And needlesly complicated installation can scare off some future contributors to the `tldr-pages` repo. That's my arguments for this proposal.

**Comment by lord63** [comment]
@t0rum  have a try the new install script, see #44
