### ISSUE TITLE
Improve the color theme

### ISSUE THREAD

**Issue by lord63** [lord63/tldr.py#7]
Currently, the default color theme is:

```
    colors = {
        "description": "blue",
        "usage": "green",
        "command": "cyan"
    }
```

`tldr.py` use `click` as the CLI package, the colors that `click` supports are:
- black (might be a gray)
- red
- green
- yellow (might be an orange)
- blue
- magenta
- cyan
- white (might be light gray)
- reset (reset the color code only)

you can find the documentation [here](http://click.pocoo.org/5/api/#click.style).

[parser.py](https://github.com/lord63/tldr.py/blob/master/tldr/parser.py) shows how `tldr.py` parse the markdown file.

If you have a custom color theme and you want to share with us, you can leave your comment with the configuration and maybe with a screen shot here.

Any suggestions and feedback are welcome :heart:

**Comment by AdamGreenhill** [comment]
In my personal opinion, that blue background mixed with the green is taxing on the eyes. If you can change the background to the original terminal setting, that would be great. Click seems to have the following options:

> bg – if provided this will become the background color.
> reset (reset the color code only)

**Comment by Shir0kamii** [comment]
@AdamGreenhill I don't have a blue background but I agree with you that customizing the background color is a good thing

**Comment by AdamGreenhill** [comment]
This is the output of tldr when run I run it on openSUSE - https://imgur.com/d9TkekV

**Comment by Shir0kamii** [comment]
And this is mine when I run it on Gentoo inside Terminator : https://imgur.com/ZmGg0sI

Not only the background is different from yours, but if a sentence uses multiples lines, only the first line is colored. (discovered it now)

**Comment by lord63** [comment]
@AdamGreenhill I'm afraid that you're not using `tldr.py`. The output is not the way that `tldr.py` should have. Are you using `tldr-python-client`? The command for `tldr.py` should be `tldr find sed`.

@Shir0kamii The reason is the man page is not right,  fetch the latest pages should fix this problem.

**Comment by AdamGreenhill** [comment]
@lord63 when I execute """ pip install tldr.py; tldr init ....; tldr find sed; """ there is a whole host of errors that occur. Using "pip install tldr" is the only one that works for me.

**Comment by lord63** [comment]
@AdamGreenhill 
Could you please paste the full error log when you use `tldr.py` and tell me your environment(python version, OS platform and so on)? If there are some bugs, I'll fix them :)

**Comment by AdamGreenhill** [comment]
To answer the original question. In my opinion I think the default colourscheme should be white/white/white as differing bash prompts (or powershell for windows) might not mesh with the cyan/blue/green scheme now.

I have found that "command - blue, desc - cyan, usage - white" looks great though.

**Comment by lord63** [comment]
Everyone has his own taste, and different terminal may have different appearance, just leave it to users, they can modify it.
